FROM amazoncorretto:21-alpine-jdk AS builder

RUN apk --no-cache add make
RUN apk --no-cache add binutils

# Set working directory
WORKDIR /app

# Copy built JAR from the builder stage
COPY . .

ENV DEMO_ENV=prod

RUN ./gradlew build -x test --no-daemon

RUN $JAVA_HOME/bin/jlink \
    --add-modules jdk.unsupported,java.base,java.sql,java.naming,java.desktop,java.management,java.security.jgss,java.instrument \
    --strip-debug \
    --no-man-pages \
    --no-header-files \
    --compress=2 \
    --output /javaruntime

FROM alpine:latest

ENV JAVA_HOME=/jre
ENV PATH="${JAVA_HOME}/bin:${PATH}"

COPY --from=builder /javaruntime $JAVA_HOME

WORKDIR /app

COPY --from=builder /app/build/libs/spring-boot-demo-prod.jar /app/spring-boot-demo-prod.jar

# Expose the port
EXPOSE 4002

# Run the application
CMD ["java", "-Dspring.profiles.active=prod", "-jar", "spring-boot-demo-prod.jar"]
