FROM eclipse-temurin:21-jdk AS builder

RUN apt-get update && apt-get install -y make binutils unzip

# Set working directory
WORKDIR /app

# Copy built JAR from the builder stage
COPY . .

ENV DEMO_ENV=prod

RUN ./gradlew build -x test --no-daemon

# Create a directory for unpacking the JAR
RUN mkdir -p /app/unpacked

# Unpack the JAR file
RUN cd /app/unpacked && unzip ../build/libs/spring-boot-demo-prod.jar

# Run jdeps to analyze dependencies and save the results
RUN jdeps \
    --ignore-missing-deps \
    --print-module-deps \
    -q \
    --recursive \
    --multi-release 21 \
    --class-path="/app/unpacked/BOOT-INF/lib/*" \
    --module-path="/app/unpacked/BOOT-INF/lib/*" \
    /app/build/libs/spring-boot-demo-prod.jar > /app/deps.info

# Run jlink to create a custom runtime image
RUN jlink \
    --verbose \
    --compress 2 \
    --strip-java-debug-attributes \
    --no-header-files \
    --no-man-pages \
    --output /javaruntime \
    --add-modules $(cat /app/deps.info)

FROM debian:buster-slim

ENV JAVA_HOME=/jre
ENV PATH="${JAVA_HOME}/bin:${PATH}"

COPY --from=builder /javaruntime $JAVA_HOME

WORKDIR /app

COPY --from=builder /app/build/libs/spring-boot-demo-prod.jar /app/spring-boot-demo-prod.jar

# Expose the port
EXPOSE 4002

# Run the application
CMD ["java", "-Dspring.profiles.active=prod", "-jar", "spring-boot-demo-prod.jar"]
