FROM amazoncorretto:21-alpine-jdk AS builder

RUN apk --no-cache add make

# Set working directory
WORKDIR /app

# Copy built JAR from the builder stage
COPY . .

ENV DEMO_ENV=prod

RUN ./gradlew build -x test --no-daemon

FROM amazoncorretto:21-alpine-jdk

WORKDIR /app

COPY --from=builder /app/build/libs/spring-boot-demo-prod.jar /app/spring-boot-demo-prod.jar

# Expose the port
EXPOSE 4002

# Run the application
CMD ["java", "-Dspring.profiles.active=prod", "-jar", "spring-boot-demo-prod.jar"]
