/*
 * This file is generated by jOOQ.
 */
package db.tables.references


import db.tables.FlywaySchemaHistory
import db.tables.Users



/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>public.users</code>.
 */
val USERS: Users = Users.USERS
